# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in Docker to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install required packages
RUN pip install --trusted-host pypi.python.org streamlit streamlit-folium neo4j geopy folium langchain openai duckduckgo-search

# Run streamlit when the container launches
CMD ["streamlit", "run", "./streamlit_carte.py"]
