FROM python:3.11

# Set the working directory
WORKDIR /usr/src/app

# Install any dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# Copy the script
COPY ./neo4j_post_install.py .

# Command to run your script
CMD ["python", "./neo4j_post_install.py"]
